"""add_user_id_to_votes

Revision ID: a5c3f9abd914
Revises: 64a3f9477db7
Create Date: 2025-06-05 13:19:25.979474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5c3f9abd914'
down_revision: Union[str, None] = '64a3f9477db7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('unique_user_rule', ['cursor_rule_id', 'user_id'])
        batch_op.create_foreign_key('fk_votes_user_id', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_votes_user_id', type_='foreignkey')
        batch_op.drop_constraint('unique_user_rule', type_='unique')
        batch_op.drop_column('user_id')
    # ### end Alembic commands ###
